SG-19789 Updates to software Licenses
shotgunsoftware/tk-core pull request #792
Opened 2020-11-10 16:44 UTC by eshokrgozar

- Added ordereddict to the requirements. 
- Added a pip freeze step to the third_party script. 
- Updated the software_credits. 
- Re-installed the third_party packages. 
- Updated six version to match in both the main source and the test dir.

2020-11-11 09:40 UTC, pscadding requested changes
I think setuptools is missing from your software credits.
Other than that, it looks great!

2020-11-11 12:29 UTC, pscadding approved these changes

2020-11-12 13:16 UTC, jfboismenu approved these changes
Aside from missing a couple of copyright notices, this looks good to me.

2020-11-12 13:16 UTC, jfboismenu commented on python/tank_vendor/requirements.txt
> +distro==1.4.0
Please add copyright notice at the top.

2020-11-12 13:16 UTC, jfboismenu commented on tests/python/requirements.txt
> +ordereddict==1.1
Are we actually using it?

2020-11-16 17:49 UTC, closed without merging