For SG-24624: allow tk-core to improve the Autodesk Idenity login UX
shotgunsoftware/tk-core pull request #844
Opened 2022-02-21 19:17 UTC by patrick-hubert-adsk

Similar work has been done in RV at the end of 2021. This needed to also be done in tk-core.

2022-03-01 21:50 UTC, patrick-hubert-adsk commented
Hi @mathurf 
These are meant to be user-facing environment variables.
How do I edit this file and where is the source ?

2022-03-02 13:20 UTC, mathurf commented
> Hi @mathurf These are meant to be user-facing environment variables. How do I edit this file and where is the source ?

It is in tk-core:
https://github.com/shotgunsoftware/tk-core/blob/master/docs/environment_variables.rst

2022-03-02 14:40 UTC, patrick-hubert-adsk commented
Updated the `environment_variables.rst` file.

2022-03-02 14:48 UTC, 000paradox000 requested changes

2022-03-02 16:56 UTC, patrick-hubert-adsk commented on python/tank/authentication/sso_saml2/core/sso_saml2_core.py
> +    from urllib.parse import urlencode
Addressed

2022-03-03 18:23 UTC, 000paradox000 approved these changes
LGTM

2022-03-09 05:43 UTC, merged