Rebranding
shotgunsoftware/tk-core pull request #946
Opened 2024-01-11 17:18 UTC by juanburgosautoglb

This PR resolves this ticket https://jira.autodesk.com/browse/SG-34066

Change all the shotgrid/shotgun occurrences in the repository.

2024-01-15 17:34 UTC, julien-lang commented
Regarding the Code Coverage issue, it's not worth the effort to add coverage for this PR. So, before the merge, I will turn this requirement off.

2024-01-16 21:46 UTC, julien-lang commented on python/tank_vendor/shotgun_api3/shotgun.py
> -            raise ShotgunError("The ShotGrid Server didn't respond with a version number. "
You can revert the changes in python/tank_vendor/shotgun_api3. This is a copy of python-api that will be made when we release a new version.

2024-02-09 19:10 UTC, julien-lang requested changes
Lot of missing asset changes. Please review the wiki page and update missing assets.

2024-02-14 16:11 UTC, carlos-villavicencio-adsk commented on docs/index.rst
> +Flow Production Tracking Toolkitt core platform, |release|
Typo here:

```suggestion
Flow Production Tracking Toolkit core platform, |release|
```

2024-02-22 21:57 UTC, julien-lang requested changes

2024-02-22 21:57 UTC, julien-lang commented on docs/resources/initializing/launch2.png
Flow Production Tracking Tool ?! No, that's not it. Let's try with "FPTR desktop app"

2024-02-22 21:57 UTC, julien-lang commented on python/tank/authentication/app_session_launcher.py
> +PRODUCT_DEFAULT = "Flow Production Tracking"
```suggestion
PRODUCT_DEFAULT = "Flow Production Tracking Toolkit"
```

2024-02-22 21:57 UTC, julien-lang commented on docs/resources/initializing/launch2.png
Hum, I mean "PTR desktop app"

2024-02-22 21:57 UTC, julien-lang commented on python/tank/authentication/login_dialog.py
> +    Indicate if we are in the context of the Flow Production Tracking.
```suggestion
    Indicate if we are in the context of the PTR desktop app.
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/authentication/login_dialog.py
> +    When the Flow Production Tracking is used, we want to disregard the value returned
```suggestion
    When the PTR desktop app is used, we want to disregard the value returned
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/authentication/resources/shotgun_logo_light_medium.png
Is it possible to make the icon bigger on the left and keep the text on 2 lines like the original (while keeping the original dimensions) please?
Otherwise, the UI looks odd.

2024-02-22 21:57 UTC, julien-lang commented on python/tank/authentication/shotgun_authenticator.py
> +      Flow Production Tracking
```suggestion
      PTR desktop app.
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/authentication/sso_saml2/core/sso_saml2_core.py
> +            # the night theme of the Flow Production Tracking impacting it. White is the safest
```suggestion
            # the night theme of the PTR desktop app impacting it. White is the safest
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/authentication/sso_saml2/core/sso_saml2_core.py
> +            #   the session_metadata property increase in size over time. The Flow Production Tracking
```suggestion
            #   the session_metadata property increase in size over time. The PTR desktop app
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/authentication/sso_saml2/core/sso_saml2_core.py
> +            #   the easy fix is to sign-out of the Flow Production Tracking (or clear_default_user()).
```suggestion
            #   the easy fix is to sign-out of the PTR desktop app (or clear_default_user()).
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/authentication/web_login_support.py
> +This can be a problem for programs not started by the Flow Production Tracking or if
Please replace to "PTR desktop app" everywhere in this file

2024-02-22 21:57 UTC, julien-lang commented on python/tank/authentication/web_login_support.py
> +At this time, only the Flow Production Tracking and Shotgun Create fully support the
Shotgun Create -> "Create app"

2024-02-22 21:57 UTC, julien-lang commented on python/tank/bootstrap/configuration_writer.py
> +        # default to the Flow Production Tracking python. We want those defaults, even with descriptor
```suggestion
        # default to the Flow Production Tracking python. We want those defaults, even with descriptor
```
```suggestion
        # default to the PTR desktop app python. We want those defaults, even with descriptor
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/bootstrap/configuration_writer.py
> +        # written out during bootstrapping to be using the ones from the Flow Production Tracking.
```suggestion
        # written out during bootstrapping to be using the ones from the PTR desktop app.
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/bootstrap/configuration_writer.py
> +        # If we're in the Flow Production Tracking
```suggestion
        # If we're in the PTR desktop app
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/bootstrap/configuration_writer.py
> +            log.debug("Flow Production Tracking process detected.")
```suggestion
            log.debug("PTR desktop app process detected.")
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/bootstrap/configuration_writer.py
> +            log.debug("Current OS interpreter will be the default Flow Production Tracking location.")
```suggestion
            log.debug("Current OS interpreter will be the default PTR desktop app location.")
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/bootstrap/constants.py
> +# default flow production tracking python installations
```suggestion
# default PTR desktop app python installations
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/bootstrap/installed_configuration.py
> +    command of the pre-zero config project creation wizard in Flow Production Tracking.
```suggestion
    command of the pre-zero config project creation wizard in PTR desktop app.
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/bootstrap/resolver.py
> +            # * Flow Production Tracking is launched using Python 2 by setting 'SHOTGUN_PYTHON_VERSION'
```suggestion
            # * PTR desktop app is launched using Python 2 by setting 'SHOTGUN_PYTHON_VERSION'
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/commands/clone_configuration.py
> +        fh.write("# Flow Production Tracking configuration file\n")
```suggestion
        fh.write("# Flow Production Tracking Toolkit configuration file\n")
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/commands/core_upgrade.py
> +        log.info("Welcome to the Flow Production Tracking update checker!")
```suggestion
        log.info("Welcome to the Flow Production Tracking Toolkit update checker!")
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/commands/core_upgrade.py
> +            "You are currently running version %s of the Flow Production Tracking"
```suggestion
            "You are currently running version %s of the Flow Production Tracking Toolkit"
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/log.py
> +            # a user navigates to a project in Flow Production Tracking, the Python
```suggestion
            # a user navigates to a project in the PTR desktop app, the Python
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/platform/engine.py
> +        Flow Production Tracking it is a scrollable list of larger icons.
```suggestion
        PTR desktop app it is a scrollable list of larger icons.
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/platform/qt/default_app_icon_256.png
This image looks pixelized. Please make a new one from SVG and rebuild the resource file

2024-02-22 21:57 UTC, julien-lang commented on python/tank/platform/qt/sg_logo_80px.png
This image looks pixelized. Please make a new one from SVG and rebuild the resource file

2024-02-22 21:57 UTC, julien-lang commented on python/tank/platform/qt/tank_logo.png
This image looks pixelized. Please make a new one from SVG and rebuild the resource file

2024-02-22 21:57 UTC, julien-lang commented on python/tank/platform/qt/tankqdialog.py
> +                "This is part of the PTR App %s" % self._bundle.name
```suggestion
                "This is part of the PTR desktop app %s" % self._bundle.name
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/platform/qt/tankqdialog.py
> +                "This is part of the PTR App %s" % self._bundle.name
```suggestion
                "This is part of the PTR desktop app %s" % self._bundle.name
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/platform/qt/tankqdialog.py
> +                "<b>Flow Production Tracking Version: </b>%s<br>" % self._bundle.tank.version
```suggestion
                "<b>Flow Production Tracking Toolkit Version: </b>%s<br>" % self._bundle.tank.version
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/util/metrics_cache.py
> +For instance, when starting Flow Production Tracking and authenticating, there is no
```suggestion
For instance, when starting the PTR desktop app and authenticating, there is no
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/util/user_settings.py
> +            - The Flow Production Tracking folder.
```suggestion
            - The PTR desktop app folder.
```

2024-02-22 21:57 UTC, julien-lang commented on python/tank/util/user_settings.py
> +            # This is the location set by users of the Flow Production Tracking in the past.
```suggestion
            # This is the location set by users of the PTR desktop app in the past.
```

2024-02-22 21:57 UTC, julien-lang commented on scripts/tank_cmd.py
> +Welcome to the Flow Production Tracking!
```suggestion
Welcome to the Flow Production Tracking Toolkit!
```

2024-02-22 21:57 UTC, julien-lang commented on scripts/tank_cmd.py
> +            "You are currently running version %s of the Flow Production Tracking." % cv
```suggestion
            "You are currently running version %s of the Flow Production Tracking Toolkit." % cv
```

2024-02-22 21:57 UTC, julien-lang commented on setup.py
> +    description="Flow Production Tracking Core API",
```suggestion
    description="Flow Production Tracking Toolkit Core API",
```

2024-02-22 21:57 UTC, julien-lang commented on tests/authentication_tests/test_app_session_launcher.py
> +        # Validate Flow Production Tracking
```suggestion
        # Validate the PTR desktop app
```

2024-02-22 21:57 UTC, julien-lang commented on tests/authentication_tests/test_app_session_launcher.py
> +                "Flow Production Tracking 3.2.1",
```suggestion
                "PTR desktop app 3.2.1",
```

2024-02-22 21:57 UTC, julien-lang commented on tests/bootstrap_tests/test_configuration_writer.py
> +        Checks that if we're running in the Flow Production Tracking we're writing the correct interpreter.
```suggestion
        Checks that if we're running in the PTR desktop app we're writing the correct interpreter.
```

2024-02-22 21:57 UTC, julien-lang commented on tests/bootstrap_tests/test_resolver.py
> +    Flow Production Tracking is launched to startup the tk-desktop
```suggestion
    the PTR desktop app is launched to startup the tk-desktop
```

2024-02-22 21:57 UTC, julien-lang commented on tests/bootstrap_tests/test_resolver.py
> +        version supporting Python 2 when Flow Production Tracking is used to startup the
```suggestion
        version supporting Python 2 when the PTR desktop app is used to startup the
```

2024-02-22 21:57 UTC, julien-lang commented on tests/descriptor_tests/test_descriptors.py
> +            r"Requires at least Flow Production Tracking.* but currently installed version is .*\.",
```suggestion
            r"Requires at least PTR desktop app.* but currently installed version is .*\.",
```

2024-02-22 21:57 UTC, julien-lang commented on tests/descriptor_tests/test_descriptors.py
> +            r"Requires at least Flow Production Tracking .* but currently installed version is .*\.",
```suggestion
            r"Requires at least PTR desktop app .* but currently installed version is .*\.",
```

2024-02-22 21:57 UTC, julien-lang commented on tests/descriptor_tests/test_descriptors.py
> +            "Requires at least Flow Production Tracking v3.3.4 but no version was specified",
```suggestion
            "Requires at least PTR desktop app v3.3.4 but no version was specified",
```

2024-02-22 21:57 UTC, julien-lang commented on tests/integration_tests/tank_commands.py
> +            r"You are currently running version HEAD of the Flow Production Tracking",
```suggestion
            r"You are currently running version HEAD of the Flow Production Tracking Toolkit",
```

2024-02-22 22:10 UTC, julien-lang requested changes
Also, please merge master to fix the branch conflict

2024-02-22 22:10 UTC, julien-lang commented on python/tank/authentication/resources/shotgun_logo_light_medium.png
Like this one: https://github.com/shotgunsoftware/tk-framework-desktopstartup/pull/114/files#diff-e70fa8da1acf4367a0f7f035ebd0d664f92583028e7e353fc38034349ff2a2a5

2024-02-23 17:22 UTC, julien-lang requested changes

2024-02-23 17:22 UTC, julien-lang commented on python/tank/authentication/resources/build_resources.sh
Please revert this!

2024-02-23 17:22 UTC, julien-lang commented on python/tank/authentication/resources/shotgun_logo_light_medium.png
Is it possible to make the icon bigger on the left and keep the text on 2 lines like the original (while keeping the original dimensions) please?
Otherwise, the UI looks odd.
https://github.com/shotgunsoftware/tk-framework-desktopstartup/pull/114/files#diff-e70fa8da1acf4367a0f7f035ebd0d664f92583028e7e353fc38034349ff2a2a5

2024-02-23 17:22 UTC, julien-lang commented on python/tank/commands/setup_project.py
> +        # Special setting used by older versions of PTR desktop app
```suggestion
        # Special setting used by older versions of the PTR desktop app
```

2024-02-23 17:22 UTC, julien-lang commented on python/tank/commands/setup_project.py
> +            "a typical basic setup of the Flow Production Tracking toolkit using the "
```suggestion
            "a typical basic setup of the Flow Production Tracking Toolkit using the "
```

2024-02-23 17:22 UTC, julien-lang commented on python/tank/platform/qt/build_resources.sh
Please revert this!

2024-02-23 17:28 UTC, julien-lang requested changes
I still see references to ShotGrid in:

- python/tank/authentication/site_info.py

I still see references to ShotGrid in assets:

- docs/resources/initializing/plugin_ids.png
- docs/resources/initializing/shared_config.png
- docs/resources/initializing/tk_project.png

2024-02-27 18:14 UTC, julien-lang approved these changes
LGTM!

2024-03-20 22:20 UTC, merged