Patch the QCheckBox class to ensure the stateChanged signal emits Qt.…
shotgunsoftware/tk-core pull request #952
Opened 2024-01-22 19:32 UTC by NorberMV

…CheckState.

2024-01-23 19:00 UTC, carlos-villavicencio-adsk approved these changes
:shipit:

2024-01-23 19:01 UTC, staceyoue requested changes
Looks good! Just a couple minor comments

2024-02-15 18:39 UTC, staceyoue submitted a review, later dismissed
This solution fixes the issue with `QtCore.Qt.Checkstate` for the `QCheckBox.stateChanged` signal, but just wanted to point out there is still the underlying issue with the QtCore.Qt.CheckState when patching PySide6. In PySide and PySide2 we could compare the QtCore.Qt.CheckState to an int, and this worked; however, in PySide6 this does not. So just wanted to note that this issue could potentially come up again in another case. Ideally we could patch the QtCore.Qt.CheckState object and override the compare/equality function so that we can compare the check state to an int with PySide6.

2024-02-15 20:10 UTC, staceyoue commented
@NorberMV sorry I just found an issue with this. Running with VRED PySide6, I think there is an infinite recursion that happens within the tk-framework-qtwidgets filtering. Investigating this now.

2024-02-15 22:32 UTC, staceyoue reviewed
Ok, so after more review, unfortunately I don't think we should include this patch for `QCheckBox` and we instead need to handle this on a case-by-case basis.

The reason being is that in this solution, every time the `stateChanged` signal is emitted, we emit it a second time (with the modified param), which in some cases causes an infinite loop of triggering the stateChanged signal (observed with SG Panel).

I tried wrapping the whole stateChanged signal, as done [here](https://github.com/shotgunsoftware/tk-core/blob/ad49df05a7701ec373a7ac4fd381024cd72e6fda/python/tank/util/pyside2_patcher.py#L176-L199), but then found that the stateChanged event can be triggered by other signals (e.g. toggle) which then cannot be intercepted only by the stateChanged emit method. So this method did not work completely.

I also tried patching the `QtCore.Qt.CheckState` enum, but did not have any success with this either. Maybe it can be done, but as of now I'm not sure how.

2024-02-16 15:06 UTC, NorberMV commented
> Ok, so after more review, unfortunately I don't think we should include this patch for `QCheckBox` and we instead need to handle this on a case-by-case basis.
> ...


I also believe that patching the Qt.Checkstate would be ideal to fix this type of comparisons of Checkstate like  `state == QtCore.Qt.Checked` I also tried that approach without success. Meanwhile, I'ill revert the patch of QCheckBox and leave only the patch of the obsolete flush method in this PR. Thanks for the investigation, @staceyoue

2024-02-16 16:13 UTC, carlos-villavicencio-adsk approved these changes
LGTM

2024-02-16 16:19 UTC, staceyoue approved these changes

2024-03-28 15:07 UTC, merged