Add PySide6 patch for QWheelEvent::delta method
shotgunsoftware/tk-core pull request #961
Opened 2024-02-22 16:47 UTC by sansrem

the QWheelEvent::delta method is currently used in tk_multi_pythonconsole/python/app/input_widget.py and output_widget.py

2024-02-22 17:08 UTC, staceyoue reviewed
@sansrem just curious what the wheel event does in the ShotGrid Python Console, can you provide a quick screen capture of this?

2024-02-22 17:24 UTC, staceyoue requested changes
LGTM! Just one comment for me

2024-02-22 17:24 UTC, staceyoue commented on python/tank/util/pyside6_patcher.py
> +            return self.angleDelta().y()
I would just add a comment here to explain why we patch the `delta` with `QWheelEvent::angleDelta().y()`
```suggestion
            # Use the more common mouse vertical scroll as the delta.
            # Horizontal scroll is ignored, use angleDelta().x() if the horizontal scroll is needed.
            return self.angleDelta().y()
```

2024-02-22 20:05 UTC, staceyoue approved these changes

2024-02-22 20:13 UTC, NorberMV approved these changes
LGTM

2024-02-23 17:42 UTC, julien-lang approved these changes

2024-02-23 18:45 UTC, merged